import pytest

from pysysml.kerml.models import ExtentOp, QualifiedName, IntValue, RealValue, UnaryOp, StringValue, InfValue, \
    CondBinOp, BinOp
from .base import _parser_for_rule


@pytest.mark.unittest
class TestKerMLTransformsOperator:
    @pytest.mark.parametrize(['text', 'expected'], [
        ('x', QualifiedName(names=['x'])),
        ('x::y', QualifiedName(names=['x', 'y'])),
        ('all x', ExtentOp(x=QualifiedName(names=['x']))),
        ('+2', UnaryOp(op='+', x=IntValue(raw='2'))),
        ('-1.4', UnaryOp(op='-', x=RealValue(raw='1.4'))),
        ('~ x::y', UnaryOp(op='~', x=QualifiedName(names=['x', 'y']))),
        ("not x::'+'", UnaryOp(op='not', x=QualifiedName(names=['x', '+']))),
        ('~ "x y z +"', UnaryOp(op='~', x=StringValue(raw='"x y z +"'))),
        ('1', IntValue(raw='1')),
        ('1.5', RealValue(raw='1.5')),
        ('.5e-2', RealValue(raw='.5e-2')),
        ('"123 456"', StringValue(raw='"123 456"')),
        ('*', InfValue()),
        ('-*', UnaryOp(op='-', x=InfValue())),
        ('1+2', BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='2'))),
        ('1-2+3',
         BinOp(op='+', x=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='2')), y=IntValue(raw='3'))),
        ('1+2*3',
         BinOp(op='+', x=IntValue(raw='1'), y=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')))),
        ('1+2..3',
         BinOp(op='..', x=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='2')), y=IntValue(raw='3'))),
        ('1*2**2',
         BinOp(op='*', x=IntValue(raw='1'), y=BinOp(op='^', x=IntValue(raw='2'), y=IntValue(raw='2')))),
        ('2**3**4',
         BinOp(op='^', x=BinOp(op='^', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='4'))),
        ('1+2 /4 or  5.0 -2 * 3',
         CondBinOp(op='or',
                   x=BinOp(op='+', x=IntValue(raw='1'), y=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='4'))),
                   y=BinOp(op='-', x=RealValue(raw='5.0'), y=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3'))))),
        ('+-+-+-3.5',
         UnaryOp(op='+', x=UnaryOp(op='-', x=UnaryOp(op='+', x=UnaryOp(op='-', x=UnaryOp(op='+', x=UnaryOp(op='-',
                                                                                                           x=RealValue(
                                                                                                               raw='3.5')))))))),
        ('-1 * +5 ** ~x',
         BinOp(op='*', x=UnaryOp(op='-', x=IntValue(raw='1')), y=BinOp(op='^', x=UnaryOp(op='+', x=IntValue(raw='5')),
                                                                       y=UnaryOp(op='~',
                                                                                 x=QualifiedName(names=['x']))))),
        ('2 ^3^4',
         BinOp(op='^', x=BinOp(op='^', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='4'))),
        ('2 ^3**4',
         BinOp(op='^', x=BinOp(op='^', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='4'))),
        ('2 **3^4',
         BinOp(op='^', x=BinOp(op='^', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='4'))),

        ('2 * 3', BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3'))),
        ('2 * 3 + 1',
         BinOp(op='+', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('3 + 1 * 2',
         BinOp(op='+', x=IntValue(raw='3'), y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='2')))),
        ('2 / 3', BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3'))),
        ('2 / 3 + 1',
         BinOp(op='+', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('3 + 1 / 2',
         BinOp(op='+', x=IntValue(raw='3'), y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='2')))),
        ('2 % 3', BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3'))),
        ('2 % 3 + 1',
         BinOp(op='+', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('3 + 1 % 2',
         BinOp(op='+', x=IntValue(raw='3'), y=BinOp(op='%', x=IntValue(raw='1'), y=IntValue(raw='2')))),

        ('2 * 3 * 1',
         BinOp(op='*', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 * 3 / 1',
         BinOp(op='/', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 * 3 % 1',
         BinOp(op='%', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 / 3 * 1',
         BinOp(op='*', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 / 3 / 1',
         BinOp(op='/', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 / 3 % 1',
         BinOp(op='%', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 % 3 * 1',
         BinOp(op='*', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 % 3 / 1',
         BinOp(op='/', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 % 3 % 1',
         BinOp(op='%', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),

        ('2 * 3 * 1 * 4',
         BinOp(op='*', x=BinOp(op='*', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 * 3 * 1 / 4',
         BinOp(op='/', x=BinOp(op='*', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 * 3 * 1 % 4',
         BinOp(op='%', x=BinOp(op='*', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 * 3 / 1 * 4',
         BinOp(op='*', x=BinOp(op='/', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 * 3 / 1 / 4',
         BinOp(op='/', x=BinOp(op='/', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 * 3 / 1 % 4',
         BinOp(op='%', x=BinOp(op='/', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 * 3 % 1 * 4',
         BinOp(op='*', x=BinOp(op='%', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 * 3 % 1 / 4',
         BinOp(op='/', x=BinOp(op='%', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 * 3 % 1 % 4',
         BinOp(op='%', x=BinOp(op='%', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 * 1 * 4',
         BinOp(op='*', x=BinOp(op='*', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 * 1 / 4',
         BinOp(op='/', x=BinOp(op='*', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 * 1 % 4',
         BinOp(op='%', x=BinOp(op='*', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 / 1 * 4',
         BinOp(op='*', x=BinOp(op='/', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 / 1 / 4',
         BinOp(op='/', x=BinOp(op='/', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 / 1 % 4',
         BinOp(op='%', x=BinOp(op='/', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 % 1 * 4',
         BinOp(op='*', x=BinOp(op='%', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 % 1 / 4',
         BinOp(op='/', x=BinOp(op='%', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 / 3 % 1 % 4',
         BinOp(op='%', x=BinOp(op='%', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 * 1 * 4',
         BinOp(op='*', x=BinOp(op='*', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 * 1 / 4',
         BinOp(op='/', x=BinOp(op='*', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 * 1 % 4',
         BinOp(op='%', x=BinOp(op='*', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 / 1 * 4',
         BinOp(op='*', x=BinOp(op='/', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 / 1 / 4',
         BinOp(op='/', x=BinOp(op='/', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 / 1 % 4',
         BinOp(op='%', x=BinOp(op='/', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 % 1 * 4',
         BinOp(op='*', x=BinOp(op='%', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 % 1 / 4',
         BinOp(op='/', x=BinOp(op='%', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 % 3 % 1 % 4',
         BinOp(op='%', x=BinOp(op='%', x=BinOp(op='%', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),

        ('2 + 3 + 1',
         BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 + 3 - 1',
         BinOp(op='-', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 - 3 + 1',
         BinOp(op='+', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 - 3 - 1',
         BinOp(op='-', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 + 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 - 4',
         BinOp(op='-', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 - 1 + 4',
         BinOp(op='+', x=BinOp(op='-', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 - 1 - 4',
         BinOp(op='-', x=BinOp(op='-', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 - 1 + 4',
         BinOp(op='+', x=BinOp(op='-', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 - 4',
         BinOp(op='-', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 + 1 - 4',
         BinOp(op='-', x=BinOp(op='+', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 - 1 + 4',
         BinOp(op='+', x=BinOp(op='-', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 - 1 - 4',
         BinOp(op='-', x=BinOp(op='-', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 - 1 + 4',
         BinOp(op='+', x=BinOp(op='-', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 + 1 - 4',
         BinOp(op='-', x=BinOp(op='+', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 - 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 - 4',
         BinOp(op='-', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 - 1 + 4',
         BinOp(op='+', x=BinOp(op='-', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 - 1 - 4',
         BinOp(op='-', x=BinOp(op='-', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 - 1 + 4',
         BinOp(op='+', x=BinOp(op='-', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 - 4',
         BinOp(op='-', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),
        ('2 + 3 + 1 + 4',
         BinOp(op='+', x=BinOp(op='+', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1')),
               y=IntValue(raw='4'))),

        ('2..3', BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3'))),
        ('2..x', BinOp(op='..', x=IntValue(raw='2'), y=QualifiedName(names=['x']))),
        ('2..-3',
         BinOp(op='..', x=IntValue(raw='2'), y=UnaryOp(op='-', x=IntValue(raw='3')))),
        ('2 .. 3  + 1',
         BinOp(op='..', x=IntValue(raw='2'), y=BinOp(op='+', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 .. 3  - 1',
         BinOp(op='..', x=IntValue(raw='2'), y=BinOp(op='-', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 .. 3  * 1',
         BinOp(op='..', x=IntValue(raw='2'), y=BinOp(op='*', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 .. 3  / 1',
         BinOp(op='..', x=IntValue(raw='2'), y=BinOp(op='/', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 + 3  .. 1',
         BinOp(op='..', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 - 3  .. 1',
         BinOp(op='..', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 * 3  .. 1',
         BinOp(op='..', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 / 3  .. 1',
         BinOp(op='..', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 + 3  .. 1 + 4',
         BinOp(op='..', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  .. 1 - 4',
         BinOp(op='..', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  .. 1 * 4',
         BinOp(op='..', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  .. 1 / 4',
         BinOp(op='..', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  .. 1 + 4',
         BinOp(op='..', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  .. 1 - 4',
         BinOp(op='..', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  .. 1 * 4',
         BinOp(op='..', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  .. 1 / 4',
         BinOp(op='..', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  .. 1 + 4',
         BinOp(op='..', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  .. 1 - 4',
         BinOp(op='..', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  .. 1 * 4',
         BinOp(op='..', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  .. 1 / 4',
         BinOp(op='..', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  .. 1 + 4',
         BinOp(op='..', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  .. 1 - 4',
         BinOp(op='..', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  .. 1 * 4',
         BinOp(op='..', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  .. 1 / 4',
         BinOp(op='..', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),

        ('2 < 3', BinOp(op='<', x=IntValue(raw='2'), y=IntValue(raw='3'))),
        ('2 < x', BinOp(op='<', x=IntValue(raw='2'), y=QualifiedName(names=['x']))),
        ('2 < -3.0',
         BinOp(op='<', x=IntValue(raw='2'), y=UnaryOp(op='-', x=RealValue(raw='3.0')))),
        ('2 > 3', BinOp(op='>', x=IntValue(raw='2'), y=IntValue(raw='3'))),
        ('2 > x', BinOp(op='>', x=IntValue(raw='2'), y=QualifiedName(names=['x']))),
        ('2 > -3.0',
         BinOp(op='>', x=IntValue(raw='2'), y=UnaryOp(op='-', x=RealValue(raw='3.0')))),
        ('2 <= 3', BinOp(op='<=', x=IntValue(raw='2'), y=IntValue(raw='3'))),
        ('2 <= x', BinOp(op='<=', x=IntValue(raw='2'), y=QualifiedName(names=['x']))),
        ('2 <= -3.0',
         BinOp(op='<=', x=IntValue(raw='2'), y=UnaryOp(op='-', x=RealValue(raw='3.0')))),
        ('2 >= 3', BinOp(op='>=', x=IntValue(raw='2'), y=IntValue(raw='3'))),
        ('2 >= x', BinOp(op='>=', x=IntValue(raw='2'), y=QualifiedName(names=['x']))),
        ('2 >= -3.0',
         BinOp(op='>=', x=IntValue(raw='2'), y=UnaryOp(op='-', x=RealValue(raw='3.0')))),
        ('2 < 3  + 1',
         BinOp(op='<', x=IntValue(raw='2'), y=BinOp(op='+', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 < 3  - 1',
         BinOp(op='<', x=IntValue(raw='2'), y=BinOp(op='-', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 < 3  * 1',
         BinOp(op='<', x=IntValue(raw='2'), y=BinOp(op='*', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 < 3  / 1',
         BinOp(op='<', x=IntValue(raw='2'), y=BinOp(op='/', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 < 3  .. 1',
         BinOp(op='<', x=IntValue(raw='2'), y=BinOp(op='..', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 > 3  + 1',
         BinOp(op='>', x=IntValue(raw='2'), y=BinOp(op='+', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 > 3  - 1',
         BinOp(op='>', x=IntValue(raw='2'), y=BinOp(op='-', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 > 3  * 1',
         BinOp(op='>', x=IntValue(raw='2'), y=BinOp(op='*', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 > 3  / 1',
         BinOp(op='>', x=IntValue(raw='2'), y=BinOp(op='/', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 > 3  .. 1',
         BinOp(op='>', x=IntValue(raw='2'), y=BinOp(op='..', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 <= 3  + 1',
         BinOp(op='<=', x=IntValue(raw='2'), y=BinOp(op='+', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 <= 3  - 1',
         BinOp(op='<=', x=IntValue(raw='2'), y=BinOp(op='-', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 <= 3  * 1',
         BinOp(op='<=', x=IntValue(raw='2'), y=BinOp(op='*', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 <= 3  / 1',
         BinOp(op='<=', x=IntValue(raw='2'), y=BinOp(op='/', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 <= 3  .. 1',
         BinOp(op='<=', x=IntValue(raw='2'), y=BinOp(op='..', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 >= 3  + 1',
         BinOp(op='>=', x=IntValue(raw='2'), y=BinOp(op='+', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 >= 3  - 1',
         BinOp(op='>=', x=IntValue(raw='2'), y=BinOp(op='-', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 >= 3  * 1',
         BinOp(op='>=', x=IntValue(raw='2'), y=BinOp(op='*', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 >= 3  / 1',
         BinOp(op='>=', x=IntValue(raw='2'), y=BinOp(op='/', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 >= 3  .. 1',
         BinOp(op='>=', x=IntValue(raw='2'), y=BinOp(op='..', x=IntValue(raw='3'), y=IntValue(raw='1')))),
        ('2 + 3  < 1',
         BinOp(op='<', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 - 3  < 1',
         BinOp(op='<', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 * 3  < 1',
         BinOp(op='<', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 / 3  < 1',
         BinOp(op='<', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 .. 3  < 1',
         BinOp(op='<', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 + 3  > 1',
         BinOp(op='>', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 - 3  > 1',
         BinOp(op='>', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 * 3  > 1',
         BinOp(op='>', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 / 3  > 1',
         BinOp(op='>', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 .. 3  > 1',
         BinOp(op='>', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 + 3  <= 1',
         BinOp(op='<=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 - 3  <= 1',
         BinOp(op='<=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 * 3  <= 1',
         BinOp(op='<=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 / 3  <= 1',
         BinOp(op='<=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 .. 3  <= 1',
         BinOp(op='<=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 + 3  >= 1',
         BinOp(op='>=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 - 3  >= 1',
         BinOp(op='>=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 * 3  >= 1',
         BinOp(op='>=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 / 3  >= 1',
         BinOp(op='>=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 .. 3  >= 1',
         BinOp(op='>=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')), y=IntValue(raw='1'))),
        ('2 + 3  < 1 + 4',
         BinOp(op='<', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  < 1 - 4',
         BinOp(op='<', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  < 1 * 4',
         BinOp(op='<', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  < 1 / 4',
         BinOp(op='<', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  < 1 .. 4',
         BinOp(op='<', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  < 1 + 4',
         BinOp(op='<', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  < 1 - 4',
         BinOp(op='<', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  < 1 * 4',
         BinOp(op='<', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  < 1 / 4',
         BinOp(op='<', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  < 1 .. 4',
         BinOp(op='<', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  < 1 + 4',
         BinOp(op='<', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  < 1 - 4',
         BinOp(op='<', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  < 1 * 4',
         BinOp(op='<', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  < 1 / 4',
         BinOp(op='<', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  < 1 .. 4',
         BinOp(op='<', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  < 1 + 4',
         BinOp(op='<', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  < 1 - 4',
         BinOp(op='<', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  < 1 * 4',
         BinOp(op='<', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  < 1 / 4',
         BinOp(op='<', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  < 1 .. 4',
         BinOp(op='<', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  < 1 + 4',
         BinOp(op='<', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  < 1 - 4',
         BinOp(op='<', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  < 1 * 4',
         BinOp(op='<', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  < 1 / 4',
         BinOp(op='<', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  < 1 .. 4',
         BinOp(op='<', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  > 1 + 4',
         BinOp(op='>', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  > 1 - 4',
         BinOp(op='>', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  > 1 * 4',
         BinOp(op='>', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  > 1 / 4',
         BinOp(op='>', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  > 1 .. 4',
         BinOp(op='>', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  > 1 + 4',
         BinOp(op='>', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  > 1 - 4',
         BinOp(op='>', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  > 1 * 4',
         BinOp(op='>', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  > 1 / 4',
         BinOp(op='>', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  > 1 .. 4',
         BinOp(op='>', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  > 1 + 4',
         BinOp(op='>', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  > 1 - 4',
         BinOp(op='>', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  > 1 * 4',
         BinOp(op='>', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  > 1 / 4',
         BinOp(op='>', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  > 1 .. 4',
         BinOp(op='>', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  > 1 + 4',
         BinOp(op='>', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  > 1 - 4',
         BinOp(op='>', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  > 1 * 4',
         BinOp(op='>', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  > 1 / 4',
         BinOp(op='>', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  > 1 .. 4',
         BinOp(op='>', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  > 1 + 4',
         BinOp(op='>', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  > 1 - 4',
         BinOp(op='>', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  > 1 * 4',
         BinOp(op='>', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  > 1 / 4',
         BinOp(op='>', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  > 1 .. 4',
         BinOp(op='>', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  <= 1 + 4',
         BinOp(op='<=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  <= 1 - 4',
         BinOp(op='<=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  <= 1 * 4',
         BinOp(op='<=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  <= 1 / 4',
         BinOp(op='<=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  <= 1 .. 4',
         BinOp(op='<=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  <= 1 + 4',
         BinOp(op='<=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  <= 1 - 4',
         BinOp(op='<=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  <= 1 * 4',
         BinOp(op='<=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  <= 1 / 4',
         BinOp(op='<=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  <= 1 .. 4',
         BinOp(op='<=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  <= 1 + 4',
         BinOp(op='<=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  <= 1 - 4',
         BinOp(op='<=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  <= 1 * 4',
         BinOp(op='<=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  <= 1 / 4',
         BinOp(op='<=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  <= 1 .. 4',
         BinOp(op='<=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  <= 1 + 4',
         BinOp(op='<=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  <= 1 - 4',
         BinOp(op='<=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  <= 1 * 4',
         BinOp(op='<=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  <= 1 / 4',
         BinOp(op='<=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  <= 1 .. 4',
         BinOp(op='<=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  <= 1 + 4',
         BinOp(op='<=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  <= 1 - 4',
         BinOp(op='<=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  <= 1 * 4',
         BinOp(op='<=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  <= 1 / 4',
         BinOp(op='<=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  <= 1 .. 4',
         BinOp(op='<=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  >= 1 + 4',
         BinOp(op='>=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  >= 1 - 4',
         BinOp(op='>=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  >= 1 * 4',
         BinOp(op='>=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  >= 1 / 4',
         BinOp(op='>=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 + 3  >= 1 .. 4',
         BinOp(op='>=', x=BinOp(op='+', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  >= 1 + 4',
         BinOp(op='>=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  >= 1 - 4',
         BinOp(op='>=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  >= 1 * 4',
         BinOp(op='>=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  >= 1 / 4',
         BinOp(op='>=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 - 3  >= 1 .. 4',
         BinOp(op='>=', x=BinOp(op='-', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  >= 1 + 4',
         BinOp(op='>=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  >= 1 - 4',
         BinOp(op='>=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  >= 1 * 4',
         BinOp(op='>=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  >= 1 / 4',
         BinOp(op='>=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 * 3  >= 1 .. 4',
         BinOp(op='>=', x=BinOp(op='*', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  >= 1 + 4',
         BinOp(op='>=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  >= 1 - 4',
         BinOp(op='>=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  >= 1 * 4',
         BinOp(op='>=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  >= 1 / 4',
         BinOp(op='>=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 / 3  >= 1 .. 4',
         BinOp(op='>=', x=BinOp(op='/', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  >= 1 + 4',
         BinOp(op='>=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='+', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  >= 1 - 4',
         BinOp(op='>=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='-', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  >= 1 * 4',
         BinOp(op='>=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='*', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  >= 1 / 4',
         BinOp(op='>=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='/', x=IntValue(raw='1'), y=IntValue(raw='4')))),
        ('2 .. 3  >= 1 .. 4',
         BinOp(op='>=', x=BinOp(op='..', x=IntValue(raw='2'), y=IntValue(raw='3')),
               y=BinOp(op='..', x=IntValue(raw='1'), y=IntValue(raw='4')))),
    ])
    @pytest.mark.focus
    def test_owned_expression(self, text, expected):
        parser = _parser_for_rule('owned_expression')
        if isinstance(expected, type) and issubclass(expected, Exception):
            with pytest.raises(expected):
                _ = parser(text)
        else:
            v, rules = parser(text)
            assert v == expected
            # assert 'owned_expression' in rules
